services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: book_record
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_record
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
